[package]
name = "advent-of-code-2021"
version = "0.1.0"
authors = ["Jason Miller <contact@jasonmiller.nl>"]
edition = "2021"

[dependencies]
clap = "3.0.0-beta.5"
regex = "1.5.4"
lazy_static = "1.4.0"
anyhow = "1.0.51"
thiserror = "1.0.30"
itertools = "0.10.1"
